stages:
  - deploy

variables:
  APP_NAME: RPush-server


deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  tags:
    - prod
  environment:
    name: production
    url: https://push.apps.mosreg.ru/
  only:
    - master
  script:
    - git-push ssh://dokku@int.apps.mosreg.ru:22/$APP_NAME
